# Generated by Django 3.1 on 2021-05-11 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('contact', models.CharField(default=None, max_length=10)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('dept', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('time', models.IntegerField(default=30)),
                ('starttime', models.DateField(default=django.utils.timezone.now)),
                ('projshortdesc', models.TextField(default=None)),
                ('field', models.CharField(max_length=20)),
                ('number_of_people', models.IntegerField()),
                ('created_by', models.ManyToManyField(to='connect.Member')),
            ],
        ),
    ]
