# Generated by Django 3.1 on 2021-05-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='field',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('field', models.CharField(default=None, max_length=20)),
                ('created_by', models.ManyToManyField(to='connect.Member')),
            ],
        ),
    ]
