# Generated by Django 3.1 on 2021-05-14 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_auto_20210511_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='connect.member')),
                ('total', models.IntegerField(default=0)),
                ('data', models.BinaryField()),
            ],
        ),
    ]
