# Generated by Django 3.1 on 2021-05-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='connect.member', unique=True),
        ),
    ]
