# Generated by Django 3.1 on 2021-05-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_auto_20210515_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='data',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blogdata',
            field=models.BinaryField(default=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projdata',
            field=models.BinaryField(default=None),
        ),
    ]
