# Generated by Django 3.1 on 2021-05-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_auto_20210515_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='total',
            new_name='totalb',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totalp',
            field=models.IntegerField(default=0),
        ),
    ]
