# Generated by Django 3.1 on 2021-05-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_auto_20210515_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='connect.Member'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ManyToManyField(related_name='created_by', to='connect.Member'),
        ),
    ]
