# Generated by Django 3.1 on 2021-05-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0009_auto_20210515_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(related_name='blikes', to='connect.Member'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_by',
            field=models.ManyToManyField(related_name='createdb_by', to='connect.Member'),
        ),
    ]
