# Generated by Django 3.1 on 2021-05-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0010_auto_20210515_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='likes',
        ),
    ]
