# Generated by Django 3.1 on 2021-05-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0011_auto_20210515_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_by',
            field=models.ManyToManyField(to='connect.Member'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ManyToManyField(to='connect.Member'),
        ),
    ]
