# Generated by Django 3.1 on 2021-05-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0012_auto_20210515_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='liked_blogs',
            field=models.BinaryField(default=None),
        ),
        migrations.AddField(
            model_name='member',
            name='liked_projects',
            field=models.BinaryField(default=None),
        ),
    ]
