# Generated by Django 3.1 on 2021-05-16 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0013_auto_20210515_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='liked_blogs',
        ),
        migrations.RemoveField(
            model_name='member',
            name='liked_projects',
        ),
    ]
