# Generated by Django 3.1 on 2021-05-17 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0014_auto_20210516_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
