# Generated by Django 3.1 on 2021-05-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0015_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='techstack',
            field=models.CharField(default='programming', max_length=50),
        ),
    ]
